# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uZc0rxNTI46nTVvJd8I4keIwDfYYrlD1
"""

import pandas as pd
import numpy as np

emp_file = pd.read_csv("employee.csv")
emp_file.head()

import pandas as pd
import numpy as np

emp_file = pd.read_csv("employee.csv")
emp_file.info()
emp_file.describe()

emp_file.isnull().sum()

emp_file["salary"].fillna(emp_file["salary"].mean(), inplace=True)

emp_file.isnull().sum()

emp_file.drop_duplicates(inplace=True)

emp_file["salary"].mean()

emp_file["department"].value_counts()

emp_file.groupby("department")["salary"].mean()

emp_file[emp_file["age"] > 35]

emp_file.nlargest(5, "salary")

pd.pivot_table(emp_file,
               values="salary",
               index="department",
               aggfunc="mean")

emp_file.to_csv("cleaned_employee_data.csv")